//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maersk_Line
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public int ShipID { get; set; }
        public int ContainerID { get; set; }
        public double Price { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Departure { get; set; }
        public string Destination { get; set; }
    }
}
